title: "Fjällklätterprojektet"
email: "fjallklatterprojektet@gmail.com"
instagram_username: "fjallklatterprojektet"
description: "Fjällklätterprojektets hemsida"
baseurl: ""
url: "https://fjallklatterprojektet.github.io/"
timezone: "Europe/Stockholm"
plugins:
  - jekyll-feed
kramdown:
  footnote_backlink: ""
