title: "Fj채llkl채tterprojektet"
email: "fjallklatterprojektet@gmail.com"
instagram_username: "fjallolle"
description: "Fj채llkl채tterprojektets hemsida"
baseurl: ""
url: "https://fjallklatterprojektet.github.io/"
plugins:
  - jekyll-feed
